// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`

  GET_MESSAGES_REQUEST
  GET_MESSAGES_SUCCESS
  GET_MESSAGES_FAILURE

  UPDATE_MESSAGES_REQUEST
  UPDATE_MESSAGES_SUCCESS
  UPDATE_MESSAGES_FAILURE

  ADD_MESSAGE_REQUEST
  ADD_MESSAGE_SUCCESS
  ADD_MESSAGE_FAILURE

  DELETE_MESSAGE_REQUEST
  DELETE_MESSAGE_SUCCESS
  DELETE_MESSAGE_FAILURE

`)
